//
// ;*** define your project wide constants here
// 
// ;*** I like to keep memory locations at top of this file
//

PMG = $5000;  // and sometimes I like to do some relative addressing
SPRITE = $6000;
//CHARSET_ADDRESS = FREE_BOTTOM;
//DISPLAY_LIST_ADDRESS = CHARSET_ADDRESS + $400; 
//VIDEO_RAM_ADDRESS = DISPLAY_LIST_ADDRESS + $100; 
//STRINGS_ADDRESS = VIDEO_RAM_ADDRESS + $400;

//RMT_PLAYER_ADDRESS = $8000;
//RMT_MODULE_ADDRESS = $8800;

// ;*** and here goes all other stuff

NONE = $ff;


